# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define p = Character("Pheemail")

init python:
    def shuffle_answers(x):
        renpy.random.shuffle(x)
        return x

# The game starts here.

label start:
    
    $ correct = 0
    $ total = 0             # result of quiz game
    $ quiz_length = 81       # number of questions in one game
    $ q_to_ask = []         # list of questions to ask in one game

    # list of all possible questions
    # it consist of dictionaries, that describe each question:
    # key "question" has value of a question, key "category" makes sense for bot, key "answer" is a list of answers, that are lists [answer itself, right/wrong]
    # the order of this keys is not matter

    # $ question1 = {"category": "Biology", "question": "", "answer": [ ["", "right"], ["", "wrong"], ["", "wrong" ]]}
    # $ question2 = {"category": "Biology", "question": "", "answer": [ ["", "right"], ["", "wrong"], ["", "wrong" ]]}
    # $ question3 = {"category": "Biology", "question": "", "answer": [ ["", "right"], ["", "wrong"], ["", "wrong" ]]}
    # $ question4 = {"category": "Biology", "question": "", "answer": [ ["", "right"], ["", "wrong"], ["", "wrong" ]]}
    # $ question5 = {"category": "Biology", "question": "", "answer": [ ["", "right"], ["", "wrong"], ["", "wrong" ]]}
    # $ question6 = {"category": "Biology", "question": "", "answer": [ ["", "right"], ["", "wrong"], ["", "wrong" ]]}
    # $ question7 = {"category": "Biology", "question": "", "answer": [ ["", "right"], ["", "wrong"], ["", "wrong" ]]}
    # $ question8 = {"category": "Biology", "question": "", "answer": [ ["", "right"], ["", "wrong"], ["", "wrong" ]]}
    # $ question9 = {"category": "Biology", "question": "", "answer": [ ["", "right"], ["", "wrong"], ["", "wrong" ]]}
    # $ question10 = {"category": "Biology", "question": "", "answer": [ ["", "right"], ["", "wrong"], ["", "wrong" ]]}

    $ question1 = {"category": "Biology", "question": "1. Aprox # of cells in body 2. Ratio of bacterial to eukaryotic", "answer": [ ["37 trillion 10:1", "right"], ["28 billion 2 million:1", "wrong"], ["153 trillion 1:1", "wrong" ]]}
    $ question2 = {"category": "Biology", "question": "Which is the tenet that is CORRECT regarding cell theory?", "answer": [ ["Cells only make up eukaryotes ", "wrong"], ["There are different forms of storage for genetic information that gets passed onto future cells", "wrong"], ["1. All living things are composed of cells 2. The cell is the basic functional unit of life 3. Cells arise only from preexisting cells 4. Cells carry genetic info (DNA), passed onto daughter cells", "right"] ]}
    $ question3 = {"category": "Biology", "question": "Membrane Bound Organelles Properties RECALL: - phospholipid bilayer is hydro______ outside and hydro_____ inside - Purpose of asymmetrical? - What is the purpose of the cytosol", "answer": [ ["1. hydrophilic outside, hydrophobic inside 2. To keep hydrophilic molecules inside the cell and hydrophobic molecules out 3. Structural component of the cells", "wrong"], ["1. hydrophilic outside, hydrophobic inside 2. So it can interact with whatever with greater affinity and selectivity 3. Allows for diffusion of molecules throughout the cell", "right"], [". 1. hydrophobic outside, hydrophilic inside 2. So it can interact with whatever with greater affinity and selectivity 3. Structural component of the cells", "wrong"] ]}
    $ question4 = {"category": "Biology", "question": "Nucleus Properties - What is a main purpose of the compartmentalization of DNA in the nucleus - Explain the function of the nucleolus, how can you identify it?", "answer": [ ["1. Protects DNA from external damage 2. The function of the nucleolus is related to the synthesis of tRNA - takes approx 25% of nucleus volume, and can be seen as a dark spot", "wrong"], ["1. Compartmentalization of DNA allows you to create two distinct environments within the cell to separate transcription and translation 2. The function of the nucleolus is related to the synthesis of rRNA - takes approx 25% of nucleus volume, and can be seen as a dark spot", "right"], ["1. Protects DNA from external damage 2. The function of the nucleolus is related to the synthesis of rRNA - takes approx 25% of nucleus volume, and can be seen as a dark spot", "wrong"] ]}
    $ question5 = {"category": "Biology", "question": "Mitochondria What are the purposes of the two membranes in mitochondria (outer and inner)", "answer": [ ["Outer - contains the molecules and nz of e transport chain Inner - arranged into folds (christae), and contains the nz for ATP synthesis", "wrong"], ["Outer - arranged into folds (christae), and contains the molecules and nz of e transport chain Inner - serves as barrier between the cytosol and inner environment of the mitochondrion", "wrong"], ["Outer - serves as barrier between the cytosol and inner environment of the mitochondrion Inner - arranged into folds (christae), and contains the molecules and nz of e transport chain", "right" ]]}
    $ question6 = {"category": "Biology", "question": "Mitochondria Explain the role of christae", "answer": [ ["Christae: contains the molecules and nz of the electron transport chain - increase the surface area of inner membrane - place where proton motive force is established for ATP synthase", "right"], ["contains the molecules and nz of the electron transport chain - increase the volume of the matrix - place where proton motive force is established for ATP synthase", "wrong"], ["contains ATP synthase - increase the volume of the matrix - place where proton motive force is established for ATP synthase", "wrong" ]]}
    $ question7 = {"category": "Biology", "question": "Mitochondria How does the mitochondria replicate for cell replication?", "answer": [ ["BINARY FISSION semi autonomous", "right"], ["Produced by budding off from the ER", "wrong"], ["Undergoes mitosis autonomously", "wrong" ]]}
    $ question8 = {"category": "Biology", "question": "Explain cytoplasmic/extranuclear inheritance - PROVIDE EXAMPLES", "answer": [ ["transmission of genetic material independent of the nucleus - mitochondria, chloroplast...etc", "right"], ["Inheritance of genetic information not related to changes in nucleotides (aka epigenetic changes) – e.g., histone acetylation, DNA methylation", "wrong"], ["Transmission of RNA found in the cytoplasm – e.g., mRNA, tRNA, siRNA", "wrong" ]]}
    $ question9 = {"category": "Biology", "question": "Mitochondria Explain how the mitochondria is associated with apoptosis", "answer": [ ["Can turn off ATP production to shut down the cell", "wrong"], ["Release of nz from the electron transport chain can trigger apoptosis", "right"], ["Mitochondrial DNA contains genes for apoptosis", "wrong" ]]}
    $ question10 = {"category": "Biology", "question": "Lysosomes What type of nz are contained within them? What would happen if they were released?", "answer": [ ["the Nz are hydrolytic nz. Release of these nz would trigger autolysis directly.", "right"], ["the Nz are kinases and phosphatases. Release of these nz would trigger autolysis indirectly.", "wrong"], ["the Nz are hydrolytic nz. Release of these nz would activate other nz that would cause autolysis.", "wrong" ]]}
    
    $ question11 = {"category": "Biology", "question": "ER Explain the difference in function between the RER and the SER", "answer": [ ["RER - studded with ribosomes, which permit the translation of proteins destined for secretion diretly into its lumen ER - lacks ribosomes and is utilized primarily for lipid synthesis. Also transports proteins from RER to golgi", "right"], ["RER - studded with ribosomes; anchoring allows for more efficient translation into the cytoplasm SER - lacks ribosomes and is utilized primarily for lipid synthesis. Also transports proteins from RER to golgi", "wrong"], ["RER - studded with ribosomes, which permit the translation of proteins destined for the mitochondria SER - lacks ribosomes and is utilized primarily for the synthesis of cytoplasmic proteins. Also transports proteins from SER to golgi", "wrong" ]]}
    $ question12 = {"category": "Biology", "question": "Golgi apparatus What are some of the destinations past the golgi (3)? What happens to products WITHIN the golgi?", "answer": [ ["lysosome, plasma membrane, exocytosis addition of additional groups, introduction of signal sequences...etc", "right"], ["lysosome, cytoplasm, mitochondria; first glycosylation, addition of additional groups...etc", "wrong"], ["cytoplasm, plasma membrane, exocytosis addition of additional groups, introduction of signal sequences...etc", "wrong" ]]}
    $ question13 = {"category": "Biology", "question": "Peroxisomes What is the main thing that peroxisomes contain? One of the primary functions of peroxisomes is the breakdown of ___________ via ________.", "answer": [ ["hydrogen peroxide, breakdown of long chain fatty acids due to beta-oxidation", "right"], ["ammonium peroxide; breakdown of steroids due to oxidation", "wrong"], ["lysozymes; breakdown of reactive species due to beta-oxidation", "wrong" ]]}
    $ question14 = {"category": "Biology", "question": "Cytoskeleton What are the three types of cytoskeleton", "answer": [ ["microfilaments, intermediate filaments, and microtubules", "right"], ["intermediate filaments, intermediate tubules, and microtubules", "wrong"], ["macrotubules, intermediate tubules, and microtubules", "wrong" ]]}
    $ question15 = {"category": "Biology", "question": "Cytoskeleton - Microfilaments What are they made of What do they interact with What do they play a role in (explain what cleavage furrow is)", "answer": [ ["1. Made up for solid polymerized actin strands 2. Use ATP to generate force by interacting with myosin 3. Plays a role in cytokinesis", "right"], ["1. Made up for solid polymerized actin strands 2. Use GTP to generate force by interacting with kinesin 3. Plays a role in cytokinesis", "wrong"], ["1. Made up for solid polymerized tubulin strands 2. Use GTP to generate force by interacting with kinesin 3. Plays a role in cell transport", "wrong" ]]}
    $ question16 = {"category": "Biology", "question": "Cytokinesis - Microtubules What are they made of? What are the motor proteins that they interact with (2) What structures are they associated with (how)?", "answer": [ ["1. Hollow polymers of tubulin proteins 2. They interact with 2 types of motor proteins (kinesin + denein) 3. They make up apart of cilia and flagella (9+2 structure for cilia) - they also make up centrioles and kinetochores", "right"], ["1. Hollow polymers of tubulin proteins 2. They interact with myosin 3. They make up apart of cilia and flagella (9+2 structure for cilia) - they also make up centrioles and kinetochores", "wrong"], ["1. Hollow polymers of tubulin proteins 2. They interact with myosin 3. They make up apart of cilia and flagella (9+2 structure for cilia) and create the cleavage furrow in cytokinesis", "wrong" ]]}
    $ question17 = {"category": "Biology", "question": "Intermediate Filaments What are the four proteins that are classified in this group", "answer": [ ["Keratin, desmin, vimentin, lamins", "right"], ["Keratin, desmin, vimentin, laminins", "wrong"], ["Adherens, desmin, integrin, laminins", "wrong" ]]}
    $ question18 = {"category": "Biology", "question": "Intermediate Filaments What is the main function of intermediate filaments", "answer": [ ["involved with cell cell adhesion, maintenance of the overall integrity of the cytoskeleton - increases structural rigidity - anchoring organelles", "right"], ["Cellular transport, maintenance of the overall integrity of the cytoskeleton - increases structural rigidity - anchoring organelles", "wrong"], ["involved with cell cell adhesion, make up cilia and flagella", "wrong" ]]}
    $ question19 = {"category": "Biology", "question": "What are the four types of tissues", "answer": [ ["Connective, Epithelial, Muscle, Nervous", "right"], ["Bone, Blood, Muscle, Nervous", "wrong"], ["Connective, Structural, Endothelial, Nervous", "wrong" ]]}
    $ question20 = {"category": "Biology", "question": "Epithelial Tissue What is the underlying layer of connective tissue called?", "answer": [ ["Basement Membrane", "right"], ["Endothelium", "wrong"], ["Base membrane", "wrong" ]]}
   
    $ question21 = {"category": "Biology", "question": "Epithelial Tissue Explain what the basement membrane is", "answer": [ ["To remain as one cohesive unit, epithelial cells are tightly joined to each other and to an underlying layer of connective tissue known as the basement membrane.", "right"], ["To provide nutrients to the top layers of epithelial cells, epithelial tissue is intermixed with a network of capillaries and connective tissue known as the basement membrane.", "wrong"], ["To prevent water loss and entry of pathogens, epithelial tissue is lined with an underlying layer of tightly joined fibroblasts known as the basement membrane.", "wrong" ]]}
    $ question22 = {"category": "Biology", "question": "Epithelial Cells Explain the parenchyma", "answer": [ ["Epithelial cells are highly diverse, in most cases they make up the parenchyma (functional part of the organ) ex. kidney nephrons, liver hepatocytes", "right"], ["Epithelial cells mainly function as a protective covering for the parenchyma (functional part of the organ) ex. kidney nephrons, liver hepatocytes", "wrong"], ["The parenchyma functions to regenerate and maintain epithelial tissue", "wrong" ]]}
    $ question23 = {"category": "Biology", "question": "Epithelial Cells Are epithelial cells polarized?", "answer": [ ["Yes, they are mostly polarized and either side usually has different functions", "right"], ["Yes, they are sometimes polarized, and one side is positively charged relative to the other", "wrong"], ["No", "wrong" ]]}
    $ question24 = {"category": "Biology", "question": "Epithelial Cells Define: 1. Simple epithelia 2. Stratified Epithelia 3. Pseudostratified epithelia", "answer": [ ["1. Simple epithelia - have one layer of cells 2. Stratified Epithelia - have multiple cells 3. Pseudostratified epithelia - appear to have multiple layers due to differences in cell height, but are really only one layer of cells.", "right"], ["1. Simple epithelia – consist of simple layers of epithelial cells 2. Stratified Epithelia - have layers consisting of multiple types of epithelial cells 3. Pseudostratified epithelia - appear to have multiple cell types due to differences in cell height, but are really only one type of epithelial cells.", "wrong"], ["1. Simple epithelia - have one layer of cells 2. Stratified Epithelia – have cell of different heights 3. Pseudostratified epithelia - appear to have cells of different heights, but really consist of multiple layers of cells", "wrong" ]]}
    $ question25 = {"category": "Biology", "question": "Epithelial Cells Define: 1. Cuboidal cells - 2. Columnar cells - 3. Squamous cells -", "answer": [ ["1. Cuboidal cells - cube shaped 2. Columnar cells - long and thin 3. Squamous cells - flat and scale like", "right"], ["1. Cuboidal cells - cube shaped 2. Columnar cells - cylindrical 3. Squamous cells - spherical", "wrong"], ["1. Cuboidal cells - cube shaped 2. Columnar cells – long and thin 3. Squamous cells - spherical", "wrong" ]]}
    $ question26 = {"category": "Biology", "question": "Connective Tissue Explain what the connective tissue are responsible for making", "answer": [ ["Connective tissue is the main contributor to the stroma or support structure. - Connective Tissues produce and secrete materials such as collagen and elastin to form the extracellular matrix", "right"], ["Connective tissue is the main contributor to the stroma or support structure. - Connective Tissues produce and secrete materials such as actin and tubulin to form the extracellular matrix", "wrong"], ["Connective tissue is the main contributor to the epithelium. - Connective Tissues produce and secrete materials such as keratin to form waterproof barrier of the skin", "wrong" ]]}
    $ question27 = {"category": "Biology", "question": "Explain what the nucleoid region is - What type of cells of they exist in?", "answer": [ ["Area in prokaryotes where the single circular strand of DNA exists", "right"], ["Area in prokaryotes where rRNA is produced", "wrong"], ["Organelle in prokaryotes where the genome is contained", "wrong" ]]}
    $ question28 = {"category": "Biology", "question": "What are the three domains of life?", "answer": [ ["Archaea, Bacteria, and Eukarya", "right"], ["Fungi, Bacteria, and Eukarya", "wrong"], ["Animalia, Plants, Prokarya", "wrong" ]]}
    $ question29 = {"category": "Biology", "question": "Archaea Archaea are visually similar to _______, but are genetically and metabolically similar to _____", "answer": [ ["visually similar to bacteria, genetically/metabolically to eukaryotes", "right"], ["visually similar to single-celled eukarya; genetically/metabolically to bacteria", "wrong"], ["similar to bacteria in both ways", "wrong" ]]}
    $ question30 = {"category": "Biology", "question": "Archaea Where were they historically more common in? What would that make them? What feature were they specifically noted to be good at?", "answer": [ ["Harsh environments, extremely high temperatures Good at alternative forms of metabolism (chemosynthetic, gneerate energy from inorganics....etc)", "right"], ["A variety of environments; Good at diverse forms of metabolism (chemosynthetic, generate energy from inorganics....etc)", "wrong"], ["Harsh environments, extremely high temperatures; Very good at usual forms of metabolism (oxidative, chemosynthetic....etc)", "wrong" ]]}

    $ question31 = {"category": "Biology", "question": "mutualistic symbiotes - ; Pathogen / parasites -", "answer": [ ["mutualistic symbiotes - both humans and bacteria benefit from the relationship; Pathogen / parasites - they provide no advantage or benefit to the host, but rather cause disease", "right"], ["mutualistic symbiotes - they provide no advantage or benefit to the host, but rather cause disease; Pathogen / parasites - both humans and bacteria benefit from the relationship", "wrong"], ["mutualistic symbiotes – organisms living together, both causing harm to one another; Pathogen / parasites - they provide no advantage or benefit to the host, but rather cause disease", "wrong" ]]}
    $ question32 = {"category": "Biology", "question": "Classification of Bacteria by Shape Three main shapes: Cocci - Bacilli - Spirilli -", "answer": [ ["Cocci - spherical bacteria; Bacilli - rod shaped; Spirilli - spiral shaped", "right"], ["Cocci - cuboidal bacteria; Bacilli – ball/spherical shaped; Spirilli - spiral shaped", "wrong"], ["Cocci - spherical bacteria; Bacilli - flat shaped; Spirilli - spiral shaped", "wrong" ]]}
    $ question33 = {"category": "Biology", "question": "Obligate aerobes - anaerobes - obligate anaerobes - facultative anaerobes - aerotolerant anaerobes -", "answer": [ ["Obligate aerobes - require O2 for metabolism anaerobes - does not require O2 for metabolism obligate anaerobes - presence of O2 is toxic to them (they create reactive oxygen radicals) facultative anaerobes - can switch between aerobic and anaerobic aerotolerant anaerobes - unable to use, but not harmed by presence", "right"], ["Obligate aerobes - require O2 for metabolism; anaerobes - presence of O2 is toxic to them (they create reactive oxygen radicals); obligate anaerobes – unable to use O2 for metabolism; facultative anaerobes - can switch between aerobic and anaerobic; aerotolerant anaerobes - not harmed by presence of O2", "wrong"], ["Obligate aerobes - require O2 for metabolism; anaerobes - does not require O2 for metabolism; obligate anaerobes - presence of O2 is toxic to them (they create reactive oxygen radicals); facultative anaerobes - can switch between aerobic and anaerobic; aerotolerant anaerobes - unable to use, but not harmed by presence", "wrong" ]]}
    $ question34 = {"category": "Biology", "question": "Prokaryotic Cell structure - Cell Wall Explain the function of cell wall for prokaryotes, also why do they form them? What makes up the envelope?", "answer": [ ["Because prokaryotes do not form multicellular organisms they need to protect themselves The envelope is made up of the cell wall and cell membrane", "right"], ["Because prokaryotes do not form multicellular organisms they need to protect themselves; The envelope is made up of the cell membrane", "wrong"], [". Protection from environment and storage of proteins; The envelope is made up of the cell membrane", "wrong" ]]}
    $ question35 = {"category": "Biology", "question": "Prokaryote - Cell Wall Explain the cell stain process", "answer": [ ["1. crystal violet stain 2. Counterstain with substance called \"safranin\" *If envelope absorbs the crystal stain, it will appear deep purple, and the cell is said to be gram +ve, if unaccpted and only absorbs the counterstain then pink-red and gram -ve.", "right"], ["1. crystal violet stain 2. Counterstain with substance called \"safranin\" *If envelope absorbs the crystal stain, it will appear deep purple, and the cell is said to be gram -ve, if unaccepted and only absorbs the counterstain then pink-red and gram +ve.", "wrong"], ["1. safranin stain 2. Counterstain with crystal violet *If envelope absorbs the crystal stain, it will appear deep purple, and the cell is said to be gram -ve, if unaccepted and only absorbs the counterstain then pink-red and gram +ve.", "wrong" ]]}
    $ question36 = {"category": "Biology", "question": "Prokaryote - Cell Wall Explain what property distinguishes gram +ve cells", "answer": [ ["+ve cells contain thick layer of peptidoglycan (polymeric substance made from amino acids and sugars - Wall may also protect cell against host immune system - +ve cell walls also contain lipoteichoice acid which may activate human immune systems", "right"], ["+ve cells contain thick layer of chitin (polymeric substance made from amino acids and sugars - Wall may also protect cell against host immune system - +ve cell walls also contain lipoteichoic acid which may activate human immune systems", "wrong"], ["+ve cells have thin layer of peptidoglycan and an outer membrane which contains lipopolysaccharides", "wrong" ]]}
    $ question37 = {"category": "Biology", "question": "Prokaryotes - Cell Wall Explain what property distinguishes gram -ve cells", "answer": [ ["The lipopolysaccharide cell wall layerand the size of the peptidoglycan layer", "right"], ["", "wrong"], ["", "wrong" ]]}
    #ask for wrong answrs ^^^
    $ question38 = {"category": "Biology", "question": "Prokaryotes - Cell wall Does lipopolysacchrides (gram ___) or lipoteichoic acid (gram ___) trigger the larger inflammatory response?", "answer": [ ["lipopolysaccharides (gram -ve) trigger larger response", "right"], ["lipopolysaccharides (gram +ve) trigger larger response", "wrong"], ["lipoteichoic (gram +ve) trigger larger response", "wrong" ]]}
    $ question39 = {"category": "Biology", "question": "Prokaroyotes - Flagella - Explain chemotaxis -", "answer": [ ["the ability of cell to detect chemical stim and move toward or away from them", "right"], ["the ability of cell to transport chemicals across its membrane", "wrong"], ["the ability of cell to move chemicals in the extracellular environment", "wrong" ]]}
    $ question40 = {"category": "Biology", "question": "Prokaroyotes - Flagella What are the three parts of flagella Explain each part", "answer": [ ["Flagella are composed of filament, basal body, and hook Filament - hollow, helical structure made of flagellin Basal body - complex structure that anchors the flagellum to cytoplasmic membrane and is the motor Hook - connects the filament and basal body so that it exerts torque on filament", "right"], ["Flagella are composed of body, basal body, and hook; Body - hollow, helical structure made of flagellin; Basal body - connects the filament and basal body so that it exerts torque on filament; Hook - complex structure that anchors the flagellum to cytoplasmic membrane and is the motor", "wrong"], ["Flagella are composed of body, basal body, and hook; Body - hollow, helical structure made of tubulin; Basal body - complex structure that anchors the flagellum to cytoplasmic membrane and is the motor; Hook - connects the filament and basal body so that it exerts torque on filament", "wrong" ]]}
    
    $ question41 = {"category": "Biology", "question": "Prokaryotes - Flagella Are gram +ve and gram -ve flagella similar?", "answer": [ ["Both gram stain flagella are similar and differ only with slight differences", "right"], ["Different. Gram +ve flagella have a much longer basal body because of the thick peptidoglycan layer", "wrong"], ["Identical", "wrong" ]]}
    $ question42 = {"category": "Biology", "question": "Prokaryotes - Other organelles Does prokaryotic DNA contain histones? How about archaea", "answer": [ ["Prokaryotic DNA DOES NOT CONTAIN actual histones, (histone like proteins) Archaea contains ACTUAL histones", "right"], ["Yes, both prokaryotes and archaea have histones", "wrong"], ["Prokaryotic and Archaea DNA DO NOT CONTAIN actual histones, (histone like proteins)", "wrong" ]]}
    $ question43 = {"category": "Biology", "question": "Prokaryotes - Other organelles What organelle do prokaryotes lack? How do they get around it? What organelle do prokaryotes have another version of?", "answer": [ ["They lack mito., cell membrane used to generate ATP Prokaryotes also contain ribosomes but the (30S and 50S) (vs euk. 40S 60S)", "right"], ["They lack mito., use only glycolysis (fermentation) to generate ATP; Prokaryotes also contain ribosomes but the (30S and 50S) (vs euk. 40S 60S)", "wrong"], ["They lack mito., use only glycolysis (fermentation) to generate ATP; Prokaryotes also contain ribosomes but the (40S and 60S) (vs euk. 30S 50S)", "wrong" ]]}
    $ question44 = {"category": "Biology", "question": "Prokaryotes - Genetics/Growth Explain binary fission (and general stages)", "answer": [ ["simplest form of asexual reproduction Circular chromosome replicates and the cell begins to grow a ridge and produce 2 cells Faster than mitosis", "right"], ["simplest form of asexual reproduction; Circular chromosome replicates and the cell begins to grow a ridge, nuclear membrane breaks down, and produce 2 cells; Faster than mitosis", "wrong"], ["simplest form of asexual reproduction; Circular chromosome replicates and a second cell buds off from the parent; Faster than mitosis", "wrong" ]]}
    $ question45 = {"category": "Biology", "question": "Prokaryotes - Recombination A subset of plamids are episomes, what do they do?", "answer": [ ["Episomes are capable of integrating into the genome of the bacterium", "right"], ["Episomes always remain separate from genome of the bacterium", "wrong"], ["Episomes are found outside of the nucleolus and do not interact with the genome", "wrong" ]]}
    $ question46 = {"category": "Biology", "question": "Prokaryotes - Genetics Explain what Transformation and Congugation is", "answer": [ ["Transformation - results from the integration of foreign genetic material into the host genome. ^ Frequently taken from other lysed bacteria and common in gram -ve. Conjugation - the bacterial form of mating", "right"], ["Transformation - the bacterial form of mating. Conjugation - results from the integration of foreign genetic material into the host genome. ^ Frequently taken from other lysed bacteria and common in gram -ve.", "wrong"], ["Transformation – transfer of genetic material via a virus or viral vector (e.g. phage). Conjugation - the bacterial form of mating", "wrong" ]]}
    $ question47 = {"category": "Biology", "question": "Prokaryotes - Other organelles What organelle do prokaryotes lack? How do they get around it? What organelle do prokaryotes have another version of?", "answer": [ ["They lack mito., cell membrane used to generate ATP Prokaryotes also contain ribosomes but the (30S and 50S) (vs euk. 40S 60S)", "right"], ["They lack mito., use only glycolysis (fermentation) to generate ATP; Prokaryotes also contain ribosomes but the (30S and 50S) (vs euk. 40S 60S)", "wrong"], ["They lack mito., use only glycolysis (fermentation) to generate ATP; Prokaryotes also contain ribosomes but the (40S and 60S) (vs euk. 30S 50S)", "wrong" ]]} #45
    $ question48 = {"category": "Biology", "question": "Prokaryotes - Genetics/Growth Explain binary fission (and general stages)", "answer": [ ["simplest form of asexual reproduction Circular chromosome replicates and the cell begins to grow a ridge and produce 2 cells Faster than mitosis", "right"], ["simplest form of asexual reproduction; Circular chromosome replicates and the cell begins to grow a ridge, nuclear membrane breaks down, and produce 2 cells; Faster than mitosis", "wrong"], ["simplest form of asexual reproduction; Circular chromosome replicates and a second cell buds off from the parent; Faster than mitosis", "wrong" ]]}
    $ question49 = {"category": "Biology", "question": "Prokaryotes - Recombination A subset of plamids are episomes, what do they do?", "answer": [ ["Episomes are capable of integrating into the genome of the bacterium", "right"], ["Episomes always remain separate from genome of the bacterium", "wrong"], ["Episomes are found outside of the nucleolus and do not interact with the genome", "wrong" ]]}
    $ question50 = {"category": "Biology", "question": "Prokaryotes - Genetics Explain what Transformation and Congugation is", "answer": [ ["Transformation - results from the integration of foreign genetic material into the host genome. ^ Frequently taken from other lysed bacteria and common in gram -ve. Conjugation - the bacterial form of mating", "right"], ["Transformation - the bacterial form of mating. Conjugation - results from the integration of foreign genetic material into the host genome. ^ Frequently taken from other lysed bacteria and common in gram -ve.", "wrong"], ["Transformation – transfer of genetic material via a virus or viral vector (e.g. phage). Conjugation - the bacterial form of mating", "wrong" ]]}

    $ question51 = {"category": "Biology", "question": "Prokaryotes - genetics Explain how conjugation occurs (3 steps) Explain Hfr", "answer": [ ["1. Cells form conjugation bridge 2. donor male (+) and recipient female (-) attatch through appendage called sex pili * Bacteria must contain sex factor plasmids that contain necessary genes - F factor is a common one in ecoli 3. F factor is copied and given to the recipient cell. Can allow for rapid aqusition of antibiotic resistance ** sometimes the sex factor is on the main circular chromosome. In that case the whole chromosome gets copied and it is called HFR (high frequency recombination)", "right"], ["1. Cells form conjugation bridge 2. donor male (+) and recipient female (-) attatch their membranes together, requiring certain sex factor plasmids that contain the necessary genes - F factor is a common one in ecoli 3. F factor is copied and given to the recipient cell. Can allow for rapid aqusition of antibiotic resistance ** sometimes the sex factor is has specific polymorphisms that increase its expression - called HFR (high frequency recombination)", "wrong"], ["1. Cells form conjugation bridge 2. donor male (+) and recipient female (-) attatch through appendage called sex pili * Bacteria must contain sex factor plasmids that contain necessary genes - F factor is a common one in ecoli 3. F factor is copied and given to the recipient cell. Can allow for rapid aqusition of antibiotic resistance ** sometimes the sex factor is has specific polymorphisms that increase its expression - called HFR (high frequency recombination)", "wrong" ]]}
    $ question52 = {"category": "Biology", "question": "Prokaryotes - Transduction Explain transduction, also what does it require?", "answer": [ ["The only genetic recombination process that requires a vector (a virus that carries the genetic material from one bacterium to another). When a virus infects a bacteria and a bit of it's chromosome gets into the virus instead of viral dna. This would deliver the host bacteria DNA to a new host.", "right"], ["the bacterial form of mating where a donor male (+) and recipient female (-) attatch through appendage called sex pili * Bacteria must contain sex factor plasmids that contain necessary genes - F factor is a common one in ecoli", "wrong"], ["results from the integration of foreign genetic material into the host genome. ^ Frequently taken from other lysed bacteria and common in gram -ve.", "wrong" ]]}
    $ question53 = {"category": "Biology", "question": "Prokaryotes - Transposons Do prokaryotes have transposons?", "answer": [ ["Yes", "right"], ["No", "wrong"], ["Some", "wrong" ]]}
    $ question54 = {"category": "Biology", "question": "Prokaryotes - Growth What are the four phases of growth for bacteria", "answer": [ ["not ready", "right"], ["", "wrong"], ["", "wrong" ]]}
    $ question55 = {"category": "Biology", "question": "1.5 - Viral Genomes Explain the terms positive sense RNA and negative sense RNA and the differences between them (Something special with -ve sense)", "answer": [ ["Positive sense - implies that the gRNA may be directly translated to functional proteins bny the robosomes of the host cell Negative sense - implies that the RNA must be turned into complementary strand of RNA before being used as protein template * -ve sense carry their own RNA replicase in virion to ensure complementary strand synthesized", "right"], ["Positive sense - implies that the RNA must be turned into complementary strand of RNA before being used as protein template; Negative sense - implies that the gRNA may be directly translated to functional proteins by the ribosomes of the host cell * -ve sense carry their own rRNA in virion to ensure functional proteins are synthesized", "wrong"], ["Positive sense - implies that the gRNA may be directly translated to functional proteins by the ribosomes of the host cell; Negative sense - implies that the RNA must be turned into complementary strand of RNA before being used as protein template * -ve sense can use their own RNA replicase or the host RNA replicase", "wrong" ]]}
    $ question56 = {"category": "Biology", "question": "1.5 Viral Genomes Explain what a retrovirus is (and list model example)", "answer": [ ["enveloped, single stranded RNA virus Brings nz reverse transcriptase that turns the viral ssRNA into dsDNA that gets integrated into host genome HIV is a retrovirus", "right"], ["enveloped, single stranded DNA virus; Brings nz reverse transcriptase that turns the viral ssDNA into dsDNA that gets integrated into host genome; HIV is a retrovirus", "wrong"], ["non-enveloped, single stranded DNA virus; Brings nz reverse transcriptase that turns the viral ssDNA into dsDNA that gets integrated into host genome; HIV is a retrovirus", "wrong" ]]}
    $ question57 = {"category": "Biology", "question": "1.5 Viral Genomes List the 6 steps in life cycle of HIV", "answer": [ ["1. Virus fuses with cell and empties contents into cytoplasm 2. RT copies ssRNA and makes dsDNA 3. integrase integrates into host genome 4. Cell machinery creates more viral RNA + proteins 5. Viral RNA and proteins move toward cell membrane where they budd 6. Immature new virus uses protease to mofidy itself to mature form", "right"], ["1. Virus fuses with cell and empties contents into cytoplasm 2. RT copies ssRNA and makes dsDNA 3. dsDNA is transcribed to mRNA 4. Cell machinery creates more viral RNA + proteins 5. Viral RNA and proteins form new immature virus and lyses the cell, releasing virions 6. Immature new virus uses protease to modify itself to mature form", "wrong"], ["1. Virus fuses with cell and empties contents into cytoplasm 2. RT copies ssRNA and makes dsDNA 3. integrase integrates into host genome 4. Cell machinery creates more viral RNA + proteins 5. Viral RNA and proteins form new immature virus and lyses the cell, releasing virions 6. Immature new virus uses protease to modify itself to mature form", "wrong" ]]}
    $ question58 = {"category": "Biology", "question": "1.5 Viral Life cycle Can viruses infect any cell? What does it require and what happens after.", "answer": [ ["Viruses cannot infect ANY cell, it requires the cell to have the correct receptors. Depending on if it has a envelope (envelope will fuse into cell).", "right"], ["Viruses CAN infect ANY cell since every cell has the same genome", "wrong"], ["Some viruses can infect any cell; others can only infect certain cell types with the correct receptors.", "wrong" ]]}
    $ question59 = {"category": "Biology", "question": "1.5 Virus Explain the process of extrusion. Explain productive cycle.", "answer": [ ["Extrusion - when the virus uses exocytosis by fusing with plasma membrane, does not kill cell. \"Productive Cyclez\" - when it is not killing itelf by lysis to release virus.", "right"], ["Extrusion – process where viral enzymes extracting the viral genome from the capsid. \"Productive Cycle\" – cycle of infection, genome replication, protein production, and release of new virions – extrusion is a key step in this.", "wrong"], ["Extrusion - when a viral genome that is integrated into the host genome is spliced out by viral enzymes. \"Productive Cycle\" – this allows for new virions to made, continuing the cycle of producing virions.", "wrong" ]]}
    $ question60 = {"category": "Biology", "question": "1.5 Lytic and Lysogenic Cycles Explain the lytic and lysogenic cycles How might one be better for the virus", "answer": [ ["During lytic cycle - bacteriophase just hardcore makes more virus until cell dies (virulent) During lysogenic cycle - integrate into host genome and become \"provirus\" and replicate descretly. - Can revert back into lytic cycle if change in environment Lysogenic might be good for host as infection with one strain of phage generally makes bacterium less susceptible to superinfection (other virus infection).", "right"], ["During lytic cycle - integrate into host genome and become \"provirus\" and replicate discretely. - Can revert back into lytic cycle if change in environment; During lysogenic cycle - bacteriophage just hardcore makes more virus until cell dies (virulent); Lysogenic might be good for host as infection with one strain of phage generally makes bacterium less susceptible to superinfection (other virus infection).", "wrong"], ["During lytic cycle - bacteriophage just hardcore makes more virus until cell dies (virulent); During lysogenic cycle - integrate into host genome and become \"provirus\" and replicate discretely. – this is permanent, cannot switch to lytic cycle; Lysogenic might be good for host as infection with one strain of phage generally makes bacterium less susceptible to superinfection (other virus infection).", "wrong" ]]}

    $ question61 = {"category": "Biology", "question": "1.5 Prions and Viriods Explain prions and viriods", "answer": [ ["Prions - infectious proteins that misfold and aggregate (aggregates are hard to degrade) and interfere with cell function Viriods - Small pathogens of very short circular ssRNA that infect plants - Binds to large # of RNA sequences and silence genes in plants (prevents synthesis and disrupts cell function).", "right"], ["Prions - infectious proteins that misfold and aggregate (aggregates are hard to degrade) and interfere with cell function; Viroids - Small pathogens containing short RNA or DNA genomes protected by a viral capsid, uses host machinery to replicate", "wrong"], ["Prions - infectious proteins that misfold and replicate by altering host DNA to produce the misfolded protein; Viroids - Small pathogens containing short RNA or DNA genomes protected by a viral capsid, uses host machinery to replicate", "wrong" ]]}
    $ question62 = {"category": "Biology", "question": "2.1 All mammals share these charcteristics: (5)", "answer": [ ["milk producing mammary glands, three bones in the middle ear & one mandible, fur or hair, heterodont detinition (teeth), both sebaceous (oil-producing) and sudoriferous (sweat) glands", "right"], ["milk producing mammary glands, omnivorous, three bones in the middle ear & one mandible, give birth (viviparous as opposed to oviparous), both sebaceous (oil-producing) and sudoriferous (sweat) glands", "wrong"], ["milk producing mammary glands, heterodont detinition (teeth), omnivorous, fur or hair, both sebaceous (oil-producing) and sudoriferous (sweat) glands", "wrong" ]]}
    $ question63 = {"category": "Biology", "question": "2.1 Two groups of special mammals that birth their young a bit differently Explain: Prototherians Metatherians", "answer": [ ["Prototherians (monotremes) - encase their developing embryos within hard-shelled aminotic eggs and lay them to be hatched (aka. oviparity). (platypus, echidna) Metatherians - undergoes some development in uterus and then climbs out of the birth canal into marsupium. (koalas and kangeroos).", "right"], ["Prototherians - undergoes some development in uterus and then climbs out of the birth canal into marsupium. (koalas and kangeroos); Metatherians (monotremes) - encase their developing embryos within hard-shelled aminotic eggs and lay them to be hatched (aka. oviparity). (platypus, echidna).", "wrong"], ["Prototherians (monotremes) - encase their developing embryos within hard-shelled aminotic eggs and lay them to be hatched (aka. oviparity). (platypus, echidna); Metatherians – entire development occurs outside the uterus in the marsupium. (koalas and kangeroos).", "wrong" ]]}
    $ question64 = {"category": "Biology", "question": "2.1 What happens during the G1 stage of mitosis?", "answer": [ ["G1 - cells create organelles for energy and protein priduction and increasing in size Passage into S stage is governed by restriction point", "right"], ["G1 - cells increase in size and decondense chromatin in preparation for S stage; Passage into S stage is governed by restriction point", "wrong"], ["G1 - cells create organelles for energy and begin to unwind DNA for replication; Passage into S stage occurs when DNA is sufficiently unwound to allow for DNA synthesis to begin", "wrong" ]]}
    $ question65 = {"category": "Biology", "question": "2.1 What happens during the S stage of mitosis?", "answer": [ ["Cell replicates chromosomes into chromatids (still only have 46 chromosomes even though 92 chromatids present) *Cells have double the DNA entering G2", "right"], ["Synthesis stage - cells create organelles for energy and protein production and increasing in size", "wrong"], ["Cell synthesizes complementary strands of DNA, creating dsDNA (still only have 46 chromosomes) *Cells have double the DNA entering G2", "wrong" ]]}
    $ question66 = {"category": "Biology", "question": "2.1 what happens at the G2 stage of mitosis?", "answer": [ ["Cells pass through another quality control checkpoint Cell checks to make sure DNA replication proceeded correctly", "right"], ["Cells create organelles for energy and protein production and increasing in size; Passage into M stage is governed by restriction point", "wrong"], ["Cells pass through another quality control checkpoint Cell checks to make sure DNA has been condensed into chromosomes properly", "wrong" ]]}
    $ question67 = {"category": "Biology", "question": "2.1 Explain what p53 is and what it is responsible for", "answer": [ ["p53 is the main protein in control of the checkpoint between G1/S, also plays a role in G2/M Checks to see if DNA is okay before going on", "right"], ["p53 is the main protein in control of the checkpoint between G2/M, checks for DNA replication errors before going on", "wrong"], ["p53 is the main protein in control of the checkpoint between G1/S, also plays a role in G2/M. Checks if enough the cell has grown enough in size and number of organelles to be able to undergo cytokinesis", "wrong" ]]}
    $ question68 = {"category": "Biology", "question": "2.1 Explain what CDK is and what it's role is", "answer": [ ["cyclin dependent kindase (CDK) are the molecules that are responsible for the cell cycle. They bind to cyclins to create a CDK-activated complex. Complex can then phosphorylate transcription factors that trigger the next step of the cell cycle.", "right"], ["cyclin dependent kinase (CDK) are molecules that play a role in signal transduction. They become activated when bound to cyclic AMP (cAMP). Complex can then phosphorylate other kinases and effectors in the signal transduction cascade.", "wrong"], ["cyclin dependent kinase (CDK) are molecules are involved in mitosis. They are become activated when the cell passes the G2/M checkpoint. The active kinase can then phosphorylate proteins such as cytoskeleton components to begin mitosis.", "wrong" ]]}
    $ question69 = {"category": "Biology", "question": "2.1 Oncogenes - Tumour Suppressor Genes -", "answer": [ ["Oncogenes - When mutated, actively promote cell division Tumour Suppressor Genes - genes that are supposed to regulate cell division", "right"], ["Oncogenes - genes that are supposed to regulate cell division; Tumour Suppressor Genes - When mutated, actively promote cell division", "wrong"], ["Oncogenes - When mutated, actively promote cell division; Tumour Suppressor Genes - genes that are involved in DNA repair, preventing mutations that can lead to tumours", "wrong" ]]}
    $ question70 = {"category": "Biology", "question": "2.1 Phases of Mitosis Summary Prophase Metaphase Anaphase Telophase", "answer": [ ["Prophase - chromosomes condense, spindle forms Metaphase - chromosomes align Anaphase - sister chromatids separate Telophase - new nuclear membranes form", "right"], ["Prophase - chromosomes condense; Metaphase - spindle forms; Anaphase - sister chromatids separate; Telophase - new nuclear membranes form", "wrong"], ["Prophase - chromosomes condense; Metaphase - spindle forms; Anaphase - chromosomes align; Telophase - sister chromatids separate, new nuclear membranes form", "wrong" ]]}

    $ question71 = {"category": "Biology", "question": "Microtubules and Centrioles are found in where? What phase?", "answer": [ ["PMA phases, also, recall microtubules are found here so a&b tublin", "right"], ["All phases, also, recall microtubules are found here so a&b tublin", "wrong"], ["MAT phases, also, recall microtubules are found here so a&b tublin", "wrong" ]]}
    $ question72 = {"category": "Biology", "question": "2.2 Meiosis Meiosis I leads to - Meiosis II leads to -", "answer": [ ["Meiosis I leads to - makes haploid daughter cells - Reductional division Meiosis II leads to - divides sister chromatids without change in ploidy - equational division", "right"], ["Meiosis I leads to - divides sister chromatids without change in ploidy - equational division; Meiosis II leads to - makes haploid daughter cells - Reductional division", "wrong"], ["Meiosis I leads to - makes diploid daughter cells - Reductional division; Meiosis II leads to - makes haploid daughter cells - Second reductional division", "wrong" ]]}
    $ question73 = {"category": "Biology", "question": "2.2 Prophase I What happens during prophase 1 ? What is the role of the synaptonemal complex Define chaisma", "answer": [ ["Prophase 1 has some crossing over Synaptonemal complex is used to hold together the homologous chromosomes", "right"], ["Homologous chromosomes pair up during prophase 1 but there is no crossing over yet; Synaptonemal complex is used to hold together the homologous chromosomes", "wrong"], ["Prophase 1 involves crossing over, which holds homologous chromosomes together; Synaptonemal complex is responsible for creating the crossovers through DNA splicing and ligation", "wrong" ]]}
    $ question74 = {"category": "Biology", "question": "2.2 Explain why mendels second law of independent assortment is related to prophase 1", "answer": [ ["prophase 1 has recombination, and that allows each haploid allele at the end to have a fresh pool of genes because 2nd law - inheritenace of one allele has no affect on the likelihood of inheriting cettain alleles for other genes", "right"], ["the random orientation of homologous pairs during prophase 1 means that every gene ends up in each daughter cell. 2nd law - inheritance of one allele has no affect on the likelihood of inheriting certain alleles for other genes", "wrong"], [". the separation of homologous pairs during prophase 1 means that each pair of alleles is separated into different daughter cells 2nd law – each gamete has equal probability of having either allele", "wrong" ]]}
    $ question75 = {"category": "Biology", "question": "2.3 What does the SRY gene do? Which chromosomes is it located on?", "answer": [ ["SRY gene is the sex determining region Y it codes for a TF that initates testis differentiation and the formation of the male gonad.", "right"], ["SRY gene is the sex determining region Y it codes for a key enzyme involved in the production of testosterone.", "wrong"], ["SRY gene is the self-regulating Y gene it codes for a key transcription factor that regulates the expression of the Y chromosome.", "wrong" ]]}
    $ question76 = {"category": "Biology", "question": "What is the pathway of semen through the reproductive system S E V E N U P", "answer": [ ["S - seminiferous tubules E - epidiymis V - vas deferens E - ejaculatory duct N - nothing U - urethra P - penis", "right"], ["S - seminiferous tubules E - ejaculatory duct V - vas deferens E - epididymis N - nothing U - urethra P - penis", "wrong"], [". S – seminiferous duct E - epididymis V - vas deferens E - ejaculatory duct N – semiNal vesicles U - urethra P - penis", "wrong" ]]}
    $ question77 = {"category": "Biology", "question": "2.2 What are the two parts of the testes and what are each of their functions (including sertoli cells)", "answer": [ ["seminiferous tubules - produces sperm and nourish through sertoli cells interstitial cells of leydig - secrete testosterone and other male sex hormones", "right"], ["seminiferous tubules - secrete testosterone and other male sex hormones; interstitial cells of leydig - produces sperm and nourish through sertoli cells", "wrong"], ["seminiferous tubules - produces sperm and nourish through interstitial cells of leydig; sertoli cells - secrete testosterone and other male sex hormones", "wrong" ]]}
    $ question78 = {"category": "Biology", "question": "2.3 What is the function of the seminal vesicle What is the function of the prostate gland What is the funciton of the cowpers glands", "answer": [ ["The seminal vesicle contributes fructose to nourish sperm The prostate gland gives the fluid mildly alkaline properties so it can survive in vagina Creates a clear fluid that flushes and lubricates penis", "right"], ["The seminal vesicle contributes fructose to nourish sperm; The prostate gland creates a clear fluid that flushes and lubricates penis; Gives the fluid mildly alkaline properties so it can survive in vagina", "wrong"], ["The seminal vesicle creates a clear fluid that flushes and lubricates penis; The prostate gland contributes fructose to nourish sperm; Gives the fluid mildly alkaline properties so it can survive in vagina", "wrong" ]]}
    $ question79 = {"category": "Biology", "question": "2.3 Explain: Spermatogonia Primary Spermatocytes Secondary spermatocytes Spermatids Spermatozoa", "answer": [ ["Spermatogonia - dipoloid stem cells that create sperm Primary Spermatocytes - after replicating genetic material during S stage Secondary spermatocytes - after first meiotic division Spermatids - after they undergo meiosis II Spermatozoa - after spermatids undergo maturation", "right"], ["Spermatogonia - diploid stem cells that create sperm; Primary Spermatocytes – after mitosis of spermatogonia; Secondary spermatocytes - after replicating genetic material during S stage; Spermatids - after first meiotic division; Spermatozoa - after they undergo meiosis II", "wrong"], ["Spermatogonia - diploid stem cells that create sperm; Primary Spermatocytes - after first meiotic division; Secondary spermatocytes - after they undergo meiosis II; Spermatids - after a mitotic division; Spermatozoa - after spermatids undergo maturation", "wrong" ]]}
    $ question80 = {"category": "Biology", "question": "2.2 Where are the mitochondria located in sperm?", "answer": [ ["located in the \"midpeice\"", "right"], ["located in the \"head\"", "wrong"], ["located in the \"tail\"", "wrong" ]]}

    $ question81 = {"category": "Biology", "question": "2.2 What is the function of acrosome, is it needed?", "answer": [ ["The acrosome is the cap that covers the sperms head Derived from golgi apparatus and necesary to penetrate ovum", "right"], ["The acrosome is the cap that covers the sperms head; Derived from extracellular matrix and necessary to protect genetic material from damage", "wrong"], ["The acrosome is the midpiece region which contains the mitochondria; Derived from the main cell body and necessary to provide the sperm with sufficient energy", "wrong" ]]}
#39,52,53?

    $ q_list = [question1,question2,question3,question4,question5,question6,question7,question8,question9,question10,question11,question12,question13,question14,question15,question16,question17,question18,question19,question20,question21,question22,question23,question24,question25,question26,question27,question28,question29,question30,question31,question32,question33,question34,question35,question36,question37,question38,question39,question40,question41,question42,question43,question44,question45,question46,question47,question48,question49,question50,question51,question52,question53,question54,question55,question56,question57,question58,question59,question60,question61,question62,question63,question64,question65,question66,question67,question68,question69,question70,question71,question72,question73,question74,question75,question76,question77,question78,question79,question80,question81]

    # let's choose some questions to play with
    # while len(q_to_ask) < quiz_length:        # will work until we'll get enough questions for quiz
    #     $ a = renpy.random.choice(q_list)    # randomly pick a question from a list of all questions
    #     if a not in q_to_ask:                 # this question will be added only if we don't have it yet
    #         $ q_to_ask.append (a)

    # for x in q_list:
    #     $ q_to_ask.append (a)


    # Show a background. This uses a placeholder by default, but you can
    # add a file (named either "bg room.png" or "bg room.jpg") to the
    # images directory to show it.

    scene classroom

    # This shows a character sprite. A placeholder is used, but you can
    # replace it by adding a file named "eileen happy.png" to the images
    # directory.

    show game girl normal

    # These display lines of dialogue.

    p "You're a cringe Med Sci kid."

    p "I am going to make you a successful cringe Med Sci kid!"

    p "Time for questions!"

    call questions

# This ends the game.

return

label questions:                              # game loop
    $ a = renpy.random.choice (q_list)      # randomly pick the question from a list
    $ q_list.remove (a)                     # remove it from list to not to ask it twice

    $ b = shuffle_answers (a["answer"])        # let's shuffle answers
            
    # ugly part... next variables are necessary to fill menu
    $ question = a["question"]
    $ category = a["category"]
    $ answ_0 = b[0][0]
    $ answ_1 = b[1][0]
    $ answ_2 = b[2][0]
    # $ answ_3 = b[3][0]
    $ total += 1

    menu:
        "Category - [category]\nQ - [question]"
        "[answ_0]":
            if b[0][1] == "right":        # checks the description of question if it's the right one
                call correct
            else:
                call wrong
        "[answ_1]":
            if b[1][1] == "right":
                call correct
            else:
                call wrong
        "[answ_2]":
            if b[2][1] == "right":
                call correct
            else:
                call wrong
        # "[answ_3]":
        #     if b[3][1] == "right":
        #         call correct
        #     else:
        #         call wrong
    
    $ quiz_length -= 1
    if quiz_length > 0:
        jump questions
            
    jump total

    return

label correct:
    show game girl happy

    p "Ding! Ding! Ding! That's one hour less you will have to spend working at McDonalds to cover your medical fees!"
    
    $ correct += 1

    return

label wrong:
    show game girl frustrated

    p "That's tough! You will be stuck working at McDonald's for life!"
    
    return

label total:
    show game girl normal

    p "You've gotten [correct] questions correct out of [total] total questions."

    return